### ISSUE TITLE
Adopt logging -- or something?

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3413] opened 2019-09-23 22:05 UTC
Silence the noise of `iris` warnings through `logging` and provide clear guidance to developers on the use of `logging` and associated `logging` levels,  and when it is actually appropriate to use `warnings` in the [Iris developers guide](https://scitools.org.uk/iris/docs/latest/developers_guide/index.html).

Reference:
- [PR 3139](https://github.com/SciTools/iris/pull/3139)
- [Issue 3078](https://github.com/SciTools/iris/issues/3078)

**Comment by bjlittle** [comment] 2020-10-12 10:14
Enabled by #3785 and the inclusion of [iris.config.get_logger](https://github.com/SciTools/iris/blob/master/lib/iris/config.py#L40)

**Comment by trexfeathers** [comment] 2021-04-20 11:54
This came up in a dev discussion this morning. Having started to use logging around Iris, we would like to collectively agree on exactly _how_ we will use it.

#### Relevant concerns

* Using Iris is currently noisy with many warnings.
  * Feedback indicates this is irritating users.
  * **As already stated: switching from `warnings.warn()` to logging is an opportunity to 'quieten' the noise.**
* So far only using logging's `DEBUG` level - not always appropriate.
  * [According to the Python docs](https://docs.python.org/3/howto/logging.html#when-to-use-logging): the `WARNING` level should be used when "something unexpected happened".
  * `DEBUG` should be used for "Detailed information, typically of interest only when diagnosing problems" - it's information on what's happening, in case it might be relevant. As opposed to something we **already know** is problematic.
  *  [1 example where `WARNING` level would be more appropriate](https://github.com/SciTools/iris/blob/98baee21721826a2a3c25d9169ed7e97e16e5e12/lib/iris/common/resolve.py#L961-L969).
  * By default, using the `WARNING` level results in output to `stderr`, so keeping Iris quiet would need raising of the logger's 'level'.
* Very difficult to know when warnings are helpful and when they are irritating.
  * Logging items above or below the logger's set level is very all-or-nothing in this regard.
  * Our current experience suggests that users who want the extra information may not be satisfied with being told they can optionally interrogate the log. Users have always been able to optionally filter/suppress warnings, but we still receive irritated feedback at the standard behaviour.

**Comment by trexfeathers** [comment] 2021-04-20 11:55
#### My two cents

* Totally in favour of wholesale switching to logging.
  Logging offers the opportunity to record new helpful events, and to better structure recording events in general.
* Convert `warnings.warn()` to `logger.warning()`.
  From a Pythonic perspective we're already using the correct level.
* Raise our `logger`'s level to make `WARNING` silent at the command line.
  Pythonic or not, the volume of warnings is known to be unhelpful to many users.
* Modify our logger to raise a standard `warnings.warn()` if any `WARNING`s are recorded in the log.
  * The identical nature means that **only one warning** will be seen at the command line, no matter how many different `WARNING`s are being logged.
  * Keeps the user informed that something in the log may need their attention, without the noisy output.
  * I _think_ this could be achieved by replacing [the current `StreamHandler`](https://github.com/SciTools/iris/blob/83eead65363b85eb7c5adba312c97ab97bca8546/lib/iris/config.py#L98) with one that has a modified [`emit()` method](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler.emit), but there may be a better way.

**Comment by pp-mo** [comment] 2021-04-20 13:20
Bumped into this while working on #4099 
I'm concerned that the newer code in `iris.experimental.ugrid` is logging what in some case "should" be warnings (IMHO) as debug,
[e.g. here](https://github.com/SciTools/iris/blob/88cfb7e932b3c99af8af8bab8f4ceaa8657b7a25/lib/iris/experimental/ugrid/__init__.py#L3335)

From the [logging module description of levels](https://docs.python.org/3/howto/logging.html#when-to-use-logging), I think we should be using 'warning' when we discover and/or workaround something that "should not happen".
As it is stated there : "".

But I do agree with @trexfeathers that we could maybe engineer a default behaviour that emits a one-time message "that warning-level events have occurred".

Other thoughts:
  * the logging module can automatically [capture all warnings output](https://docs.python.org/3/library/logging.html#integration-with-the-warnings-module).  
     So maybe we use that to avoid changing lots of existing source ?
  * (however) the warnings approach allows to classify / filter warnings by Exception subclassing, ***and*** labels messages according to the source line.  I'm not sure if we will be missing some of that functionality?  **However**, by enabling us to hide things + record them elsewhere, the logging module make this much less necessary
  *  the existing warnings (notably for netcdf loading) don't seem to doing the desired 'show once only' behaviour, and I'm not sure why not.   Probably ok, when ported to logging, as in previous point

**Comment by pp-mo** [comment] 2021-04-21 14:50
## Additional note : 
From my experience on #4099 I am now suspicious of some of the existing usage.
It seems to be _obligatory_ for any `logger.log` usage to add an "extra=dict(cls=<something>)`, otherwise you get a runtime error when the logging code is actually called.  
I think this is simply due to the way the "iris.experimental.ugrid" logger [is created / defined](https://github.com/SciTools/iris/blob/mesh-data-model/lib/iris/experimental/ugrid/__init__.py#L76)

So, I **_think_** a lot of the existing calls don't have this + may be bugged.
Within existing code, I found:
  * https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/experimental/ugrid/__init__.py#L1232
  * https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/experimental/ugrid/__init__.py#L3335
  * https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/experimental/ugrid/__init__.py#L3349
  * https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/experimental/ugrid/__init__.py#L3406
  * https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/experimental/ugrid/__init__.py#L3423
  * https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/experimental/ugrid/__init__.py#L3470
  * https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/experimental/ugrid/__init__.py#L3484
 
Unfortunately I'm not just fixing these now, as I think to do that we should really add tests for these code sections
 -- so it's not just a quickie (!)

**Comment by trexfeathers** [comment] 2021-04-21 15:02
>I **_think_** a lot of the existing calls don't have this + may be bugged.

@pp-mo I'm struggling to see how this could be the case.

1. All those instances _are_ unit tested for log entries.
2. [There's also the fact that logging is already part of core Iris code, and doesn't always provide the `extra` kwarg.](https://github.com/SciTools/iris/search?q=logger.debug)

**Comment by pp-mo** [comment] 2021-04-21 18:04
> There's also the fact that logging is already part of core Iris code, and doesn't always provide the extra kwarg.

I think my point only applies to the ones in `iris.experimental.ugrid`.
Both `iris.common.resolve` and `iris.common.maths` have their own loggers _which are configured differently_, e.g. [the one in resolve.py](https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/common/resolve.py#L29).

Whereas, in `iris.common.metadata`, [its logger is defined in the same way as in experimental.ugrid](https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/common/metadata.py#L53), but all the calls there use the 'extra' keyword [like this](https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/common/metadata.py#L183-L185).

**Comment by pp-mo** [comment] 2021-04-21 18:18
> All those instances are unit tested for log entries.

After some effort, I worked this out.
Unfortunately, it's a bit horrible ...

The testing code is **_replacing_** the real logger with the one used to record in the test, so the 'real' one is not actually called.

E.G. looking at [this test](https://github.com/SciTools/iris/blob/1ed885e9ffb167d4e5b9b5908d3f763703366f2d/lib/iris/tests/unit/experimental/ugrid/test_Mesh.py#L728-L730).

So, in that test, I added another `self.mesh.dimension_names("foo", "bar", "baz")` before the logging test context.
That **_still_** didn't get an error, because the default level is wrong (> 'DEBUG'), so it isn't logging the message
But when I also add a line to set the level, I do get the error...
Test code now :
```
    def test_dimension_names(self):
        # Test defaults.
        default = ugrid.Mesh1DNames("Mesh1d_node", "Mesh1d_edge")
        self.assertEqual(default, self.mesh.dimension_names())

        // ADDED LINES
        ugrid.logger.setLevel('DEBUG')
        self.mesh.dimension_names("foo", "bar", "baz")
        // END ADDED LINES

        with self.assertLogs(ugrid.logger, level="DEBUG") as log:
            self.mesh.dimension_names("foo", "bar", "baz")
            self.assertIn("Not setting face_dimension", log.output[0]) 
   . . .
```

Now I **_do_** get an error when I run the test.
```
$ python -m unittest iris.tests.unit.experimental.ugrid.test_Mesh
.............--- Logging error ---
Traceback (most recent call last):
  File "/tmp/persistent/miniconda3/envs/irisgrib/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/tmp/persistent/miniconda3/envs/irisgrib/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/tmp/persistent/miniconda3/envs/irisgrib/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/tmp/persistent/miniconda3/envs/irisgrib/lib/python3.7/logging/__init__.py", line 580, in formatMessage
    return self._style.format(record)
  File "/tmp/persistent/miniconda3/envs/irisgrib/lib/python3.7/logging/__init__.py", line 422, in format
    return self._fmt % record.__dict__
KeyError: 'cls'
Call stack:
 . . .
```

**Comment by pp-mo** [comment] 2021-04-21 22:40
Afterthought ... 
As you said, all the logging instances are all debugged, so I was really **wrong** about needing to add more testing.

In that case, that should make it pretty easy to fix this after all, and ensure that the tests are fully exercising the code.
E.G. we can maybe work out a way to test via the existing per-module loggers, rather than replacing them ?
I still think it's a separate operation though, the decisions are totally trivial.

**Comment by bjlittle** [comment] 2021-04-22 08:54
I think we should draw this discussion to a close here on this issue.

Remember that we do now have GitHub [Discussions](https://github.com/SciTools/iris/discussions) which might be more appropriate.

Nevertheless, I'll draft an IEP to cover this. Which will promote a more concise and transparent summary of what's been proposed and how this should be applied with iris 👍

Ping @Knight

**Comment by pp-mo** [comment] 2021-04-28 08:59
Somewhat related, re improving tests of logging usage : https://github.com/SciTools/iris/pull/4106

**Comment by trexfeathers** [comment] 2022-09-27 10:51
Uncertainty at this point makes this issue inappropriate for a release - needs internal discussion

**Comment by trexfeathers** [comment] 2022-11-23 11:21
From @jamesp:

>Logging is a different use case to warning. Logging is about recording information of the activity of a system, typically an event-based system, for review later. Iris is a library, not a system. everything is deterministic in Iris. It could be appropriate for systems using Iris to employ logging, but not within Iris itself.

In conversation, we agreed that any time that Iris' behaviour deserves communication to the user should either be a `Warning` or an `Exception`. There is no case for providing the user with `DEBUG` or `INFO` level information.

**Comment by trexfeathers** [comment] 2022-11-23 11:22
If we better categorise Iris' warnings, we can then educate the user base on catching the categories they are comfortable ignoring. We could also provide one or more conveniences for opting out of some/all warnings.

It seems like the main part of solving Iris' verbosity is user education. This would also be needed with any logging-based solution.

**Comment by trexfeathers** [comment] 2022-11-23 11:24
There is of course a separate argument for implementing logging to aid Iris development. But that was not the original scope of this issue:

>Silence the noise of `iris` warnings through `logging` ...

**Comment by pp-mo** [comment] 2022-11-23 11:40
In a peloton meeting, @bsherratt clarified a couple of technical points : 
  * warnings do not have a built-in "severity level" -- though a class hierarchy could be used (in Iris) to provide multi-level control
  * logging allows building a hierarchy of loggers to control messages/recording in different specific areas, such a specific sub-modules (some of this is already [anticipated in existing code](https://github.com/SciTools/iris/blob/57647d2c413dc3b85ecdde566a6340c9e43ad83b/lib/iris/common/metadata.py#L49-L50))
  * logging doesn't really provide simple general-purpose control and reporting methods.  
    Whether warnings or logging, we should provide Iris-specific control mechanism which are easy to use.

**Comment by bjlittle** [comment] 2023-03-01 10:28
https://github.com/Delgan/loguru is a thing

**Comment by trexfeathers** [comment] 2023-09-26 11:25
Closing due to recent progress:

- Decided as a team that we want to work with Python's warnings filter, so using warnings rather than logging where warnings are needed - #5474
- Part of Iris' verbosity is due to duplicated warnings. We have made lots of progress understanding the cause of these, but still need work to prevent them - #5464 
- Remaining use of logging for debugging purposes is of speculative value ([see discussion](https://github.com/orgs/SciTools/projects/25/views/2?pane=issue&itemId=35673177)), so is at best low priority

**Closed by trexfeathers** 2023-09-26 11:25 UTC
Labels: Status: Decision Required, Dragon 🐉
