### ISSUE TITLE
PaddingError: Placeholder of length '80' too short in package scitools::udunits2-2.2.20-0.

### ISSUE THREAD

**Issue by jeixav** [SciTools/iris#2293] opened 2017-01-09 19:47 UTC
I am trying to install Iris using Conda:
`conda install -c scitools iris`

The installation fails with this message:
> PaddingError: Placeholder of length '80' too short in package scitools::udunits2-2.2.20-0.
> The package must be rebuilt with conda-build > 2.0.

I think a similar error is described in this issue: https://github.com/conda/conda/issues/4088. Is the error message accurate, was udunits built with conda-build < 2.0? Could the SciTools team rebuild the udunits2 package with conda-build > 2.0?

To reproduce this error, the Miniconda path must be long. I used: /tmp/armnkro/35722/tmp.rTJtNvkKDZ/fca90fd2-159d-47d7-9593-45f5bd5e9a45/miniconda2.

**Comment by dkillick** [comment] 2017-01-10 10:59
Thanks @jeixav - I've replicated the error you describe here. Evidently, the problem has arisen because we have not built the udunits2 package with an up-to-date version of conda-build. Do you mind if I close this issue and re-open it against SciTools/conda-recipes-scitools? I think that would be a better place for this issue as the problem is primarily a conda recipe issue and not an Iris issue. I'll link this issue to it once I've opened a replacement.

**Closed by dkillick** 2017-01-10 10:59 UTC

**Comment by jeixav** [comment] 2017-01-10 14:42
> Do you mind if I close this issue and re-open it against SciTools/conda-recipes-scitools?

Not at all. I would have submitted my issue to [conda-recipes-scitools](https://github.com/SciTools/conda-recipes-scitools) myself, but did not realize that repository exists until reading your reply. Thanks!
