### ISSUE TITLE
Certain mercator projections not loading properly

### ISSUE THREAD

**Issue by nhsavage** [SciTools/iris#3107] opened 2018-07-30 11:23 UTC
RCM data generated by the RegCM4 model for CORDEX does not load correctly with Iris 2.0:

    >>> cubeslist=iris.load('tasmax_CAM-44_MOHC-HadGEM2-ES_historical_r1i1p1_ICTP-RegCM4-3_v4_mon_19700101-19701230.nc')
    UserWarning: False eastings other than 0.0 not yet supported for Mercator projections
    warnings.warn('False eastings other than 0.0 not yet supported '
    /opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:2171: UserWarning: False northings other than 0.0 not yet supported for Mercator projections
    warnings.warn('False northings other than 0.0 not yet supported '
    /opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py:2181: UserWarning: Standard parallels other than 0.0 not yet supported for Mercator projections
    warnings.warn('Standard parallels other than 0.0 not yet '

This gives the following cordinates (x and y dim coords missing)

    air_temperature / (K)               (time: 12; -- : 157; -- : 285)
         Dimension coordinates:
              time                           x        -         -
         Auxiliary coordinates:
              latitude                       -        x         x
              longitude                      -        x         x

**Comment by nhsavage** [comment] 2018-07-30 15:14
Ruth Comer has pointed out that the warnings are still present in master: https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb#L2012

**Comment by nhsavage** [comment] 2018-10-19 08:02
I can confirm that this issue still exists with Iris 2.2.0

**Comment by pp-mo** [comment] 2021-01-06 18:39
> this might be a duplicate of #3041 but I don't have any way of checking as I don't have the latest version of Iris in any environment I can access.

Just stumbled across this.
I think #3041 fixes the warning about 'standard_parallel', but not the false_easting/northing ones.
`iris.coord_systems.Mercator` seems to be the only remaining coord-system that still does **not** support false_easting/northing,  though [the cartopy class does](https://github.com/SciTools/cartopy/blob/master/lib/cartopy/crs.py#L1004), and they are now [valid attributes for all the non-latlon grid mapping types](https://github.com/cf-convention/cf-conventions/pull/225)

It seems pretty straightforward to fix : 
  1. add the optional params in the iris Mercator class, 
  2. duplicate support code for other types within the netcdf load and save code.
  3. add some testing

So, **Do you still have an interest in this ?**
If so we can easily make it a Peloton issue.

**Comment by nhsavage** [comment] 2021-01-07 07:39
I am extremely interested in this! If it could be a Peleton issue that would be great. For context, several key regional climate models we use in our team need this and at the moment we have to regrid using cdo at the moment before loading.

**Comment by nhsavage** [comment] 2021-01-07 07:48
I can provide sample data if you need it - drop me a line and I will get back to you.

**Comment by pp-mo** [comment] 2021-01-07 09:46
> @nhsavage I can provide sample data if you need it

I only *think* I know what's needed, so it's certainly worth making sure.
I will get in touch for reference data.

**Comment by trexfeathers** [comment] 2021-11-10 10:23
We're gonna close this due to lack of progress (we all understand that each other is busy!). Feel free to re-open if you think progress can be made 🙂

**Comment by Scott-Burgan** [comment] 2022-01-19 14:47
I was advised by Will Benfold to comment on here to gauge interest in sorting this issue. I am still having this issue and I know it is something that is affecting a couple of colleagues as well. Was wondering if this would be re-visited at some point?

**Comment by wjbenfold** [comment] 2022-01-19 15:59
Thanks @Scott-Burgan for adding your interest here, we're currently pretty busy getting the 3.2 release out, but will discuss this in our next Peloton (chat of contributors about community-raised issues).
If in the meantime it seems easiest for you if any workaround you're looking at is actually a fix in Iris then feel free to put up a pull request to fix it yourself (no pressure, obviously, but we'd be happy to help if that's a route you're interested in)

**Comment by wjbenfold** [comment] 2022-01-19 16:04
> this might be a duplicate of #3041 but I don't have any way of checking as I don't have the latest version of Iris in any environment I can access.

I don't think it is, as extra kwargs have been added to cartopy's Mercator since then by the look of it. I can also reproduce this issue on the latest Iris (though the warnings don't happen any more because we removed pyke...)

**Comment by nhsavage** [comment] 2022-01-21 09:05
It's hard to be certain that it should load cleanly, but it IS cf compliant. Its hard to verify properly, because most tools rely on the 2D lat and lon coords. Could we start by seeing if cartopy can create this projection outside Iris? We can then check the 2D lat and lon against why Cartopy thinks we should have.

**Comment by nhsavage** [comment] 2022-01-21 09:44
Reading the CF conventions in more detail for Mercator projections though, I am a bit confused

https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_mercator

Map parameters:
        longitude_of_projection_origin
        Either standard_parallel (EPSG 9805) or scale_factor_at_projection_origin (EPSG 9804)
        false_easting - This parameter is optional (default is 0)
        false_northing - This parameter is optional (default is 0)

our data has 

		crs:false_easting = -12500. ;
		crs:false_northing = -12500. ;
		crs:grid_mapping_name = "mercator" ;
		crs:standard_parallel = -2. ;
		crs:latitude_of_projection_origin = -2. ;
		crs:longitude_of_projection_origin = 12. ;

so all of the REQUIRED parameters but also a latitude of projection origin. This is used by an oblique mercator however, I don't think we have that. Digging into the proj4 documentation https://proj.org/operations/projections/merc.html I think that this piece of metadata is wrong named. The proj4 string has lat_ts=-2.00 and that is not latitude of projection origin but latitude of true scale

**Comment by nhsavage** [comment] 2022-01-21 09:46
I can't quite work out how to make a cartopy projection from a proj4 string though. We have 

"+proj=merc +lat_ts=-2.00 +lon_0=12.00 +x_0=-12500. +y_0=-12500. +ellps=sphere +a=6371229. +b=6371229. +units=m +no_defs" 

but cartopy seems to want an iterable of key-value pairs. When I try and turn the string into a dictionary I get errors I can't fix

**Comment by rcomer** [comment] 2022-01-21 09:58
@nhsavage the `Projection` class has a `from_proj4` method.  Does that do what you need?

**Comment by nhsavage** [comment] 2022-01-21 10:31
@wjbenfold  ok I have created a cartopy projection, set the limits to the x and y values of the data and the extent seems by eye to be identical to the results of doing a contourf plot on the data from Iris. Therefore if cartopy can turn this into a projection (when one bit of metadata is fixed) shouldn't iris be able to use it?

**Comment by nhsavage** [comment] 2022-01-21 10:56
Code to make Cartopy projection from the proj4 parameters 

"+proj=merc +lat_ts=-2.00 +lon_0=12.00 +x_0=-12500. +y_0=-12500. +ellps=sphere +a=6371229. +b=6371229. +units=m +no_defs"

```
    ourglobe = ccrs.Globe(datum='WGS84', ellipse='sphere', 
                          semimajor_axis=6371229., 
                          semiminor_axis=6371229.)
    ourproj = ccrs.Mercator(central_longitude=12.0, 
                            min_latitude=-80.0, 
                            max_latitude=80.0, 
                            globe=ourglobe, 
                            latitude_true_scale=-2.0, 
                            false_easting=-12500., 
                            false_northing=-12500., 
                            scale_factor=None)

```

**Comment by wjbenfold** [comment] 2022-01-24 14:24
When I ncdump @Scott-Burgan's .nc file it has a `projection = "NORMER"` but no `grid_mapping` attribute, which I think may be the issue. @nhsavage could you point me to an nc file of yours that I could try?

**Comment by wjbenfold** [comment] 2022-01-24 15:50
```
air_pressure_at_sea_level / (Pa)                 (time: 24; projection_y_coordinate: 497; projection_x_coordinate: 477)
    Dimension coordinates:
        time                                          x                            -                             -
        projection_y_coordinate                       -                            x                             -
        projection_x_coordinate                       -                            -                             x
    Auxiliary coordinates:
        latitude                                      -                            x                             x
        longitude                                     -                            x                             x
    Cell methods:
        mean                                     time
    Attributes:
        CORDEX_domain                            AFR-22
        Conventions                              CF-1.7,
        ICTP_version_note                        none
```

`Default plot of cube: +proj=merc +a=6371229.0 +b=6371229.0 +lon_0=12.0 +x_0=-12500.0 +y_0=-12500.0 +units=m +lat_ts=-2.0 +no_defs +type=crs`

It works! I'll put up a PR

**Comment by wjbenfold** [comment] 2022-01-27 10:43
> my file is at:
> 
> /data/users/fris/regcm4/ psl_AFR-22_ECMWF-ERAINT_evaluation_r1i1p1_ICTP-RegCM4-7_v0_mon_197901-198012.nc

@nhsavage would you mind if I use this file as a test for Iris (meaning that it would be publically available in our test data repository). If I can't, do you have another (ideally fairly small) file that might serve that purpose?

**Comment by thomascrocker** [comment] 2022-02-24 12:16
Just to add my name to the list of people affected by this issue.

See all netCDF files located below

`/project/champ/data/cordex/output/CAM-44/ICTP`

Until this is fixed, I have to leave two models out of my analysis for a deliverable.

**Closed** 2022-03-01 09:41 UTC
Labels: Type: Enhancement, Release: Minor, Experience: Medium, Peloton 🚴‍♂️
