### ISSUE TITLE
Test failure in iris.tests.integration.test_netcdf

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#2875] opened 2017-10-27 11:01 UTC
Likely an oversight from all of the time-outs we have been seeing on Travis lately.

```
======================================================================

FAIL: test_concatenate_cell_measure_match (iris.tests.integration.test_netcdf.TestCellMeasures)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/Iris-2.0a0-py2.7.egg/iris/tests/integration/test_netcdf.py", line 258, in test_concatenate_cell_measure_match

    self.assertEqual(len(cubes), 1)

AssertionError: 2 != 1

----------------------------------------------------------------------
```

Gives further priority to #2865.

**Comment by dkillick** [comment] 2017-11-01 12:29
This test no longer fails locally or on Travis (see, for example, this [recent CI run](https://travis-ci.org/SciTools/iris/jobs/295684315#L1241)). Still going to investigate in case there really is something odd going on...

**Comment by dkillick** [comment] 2017-11-01 13:51
In fact, even if I check out 4f8b2d8 locally I can't reproduce this failure. I'm going to close this issue as "unexplained; no longer a problem."

**Closed by dkillick** 2017-11-01 13:51 UTC
Labels: Experience-needed: Low, SemVer: Patch, Type: Bug

**Comment by pelson** [comment] 2017-11-02 09:58
Thanks for checking @dkillick.
