### ISSUE TITLE
Complete v1.10 deprecations to prepare for v2.0

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#1948] opened 2016-02-23 16:28 UTC
Current list of possibles.

Important deprecations
  * [x] text rules support : to enable later removal
    * ~~#1885~~ custom save rules (now with: remaining (public) support for text-rules and rules logging)
  * [x] iris.fileformats.ff  : to enable later rebase around new "mule" fieldsfile interface, when that is made public
    * ~~#1950~~ deprecate_ff
  * [x] deprecate the pp_packing module (now replaced by mo_unpack)
    * ~~#1958~~ "Hide iris.fileformats.pp_packing behind a deprecation interface."
  * [x] tidy and rename the load pipeline
    * ~~#1941~~ "as cubes"
  * [x] fully deprecate the old-style (non-"strict") GRIB loader, including sub-modules
    * was ~~#1962~~ (done)
    * possibly still needs whatsnew for 'other' global stuff removed
    * possibly still needs reviewing, alongside #1755 (next) to ensure we haven't made any any backwards-incompatible changes, such as moving data items out of iris.fileformats.grib module
    * see also #2019 "Deprecate iris.FUTURE.strict_grib_load"
  * [x] make it possible to load GRIB1 files with the new 'strict' GRIB loader
    * ~~#1755~~ "grib1 future"  [[https://github.com/SciTools/iris-grib/pull/22 replaces]]
    * **NOTE:** I'm listing this as a requirement for 1.10, because without it there is loss of capability to load mixed GRIB1 + GRIB2 files -- which in fact various users need, as some semi-'standard' ecmwf products are like that

Other possibles:
  * [x] regrid + interpolation : to enable later tidying
  * [x] ESMPY support : update + get Travis-testable
    * ~~#2001~~
  * [x] user advice on deprecations and code maintenance
    * see #1999
  * ~~deprecate all internal module imports, to avoid user code depending on them~~
    * ~~e.g. ```import iris.analysis``` --> ```import iris.analysis as _analysis```~~

-----

**NOTE:**
> deprecate all internal module imports, to avoid user code depending on them

Does this actually work ??
```
>>> import iris
>>> hasattr(iris, 'proxy')
False
>>> from iris import proxy as _proxy
/home/h05/itpp/git/iris/iris_main/lib/iris/proxy.py:34: UserWarning: iris.proxy is deprecated in Iris v1.9. Please use lazy imports instead.
  warnings.warn('iris.proxy is deprecated in Iris v1.9. Please use lazy '
>>> hasattr(iris, 'proxy')
True
>>> 
```

**Comment by cpelley** [comment] 2016-03-24 11:41
Hi @pp-mo, when are you intending to remove/convert the pp save rules text file?

We would like to make some alterations, so I'm just checking that we won't be causing problems (unnecessary conflicts) by putting up a PR relatively soon.

Cheers

**Comment by pp-mo** [comment] 2016-04-20 10:25
> @cpelley when are you intending to remove/convert the pp save rules text file?

Sorry, I somehow missed this.
Harold Dyson mentioned it just yesterday.
We are proposing to deprecate the text rules interface in 1.10, but it cannot be actually removed until 2.0 (and at least 6 months, if we stick to our stated rules!).
When we remove the facility itself, we'll replace the existing save rules with Python code.

Key message:  don't worry about making changes and additions to the save rules :  we will carry over all existing functionality when we migrate the rules to Python.

**Comment by rhattersley** [comment] 2016-04-20 12:00
> at least 6 months, if we stick to our stated rules

I think we should change the rules: #1976.

**Comment by hdyson** [comment] 2016-04-20 12:32
Hi @pp-mo,

The fix we spoke about yesterday is over on #1975 I may have stretched @cpelley's definition of 'relatively soon' a bit.

Thanks.

**Comment by rhattersley** [comment] 2016-04-28 13:21
#1941 is merged - is it time to tick off the corresponding item in the checklist?

**Comment by rhattersley** [comment] 2016-05-05 14:11
Trying to get my head around what's been going on with the GRIB handling. I'll probably update this comment as the murk clears.

Comparing v1.9.2 with master shows:

#1942
Removed:
- iris.fileformats.grib.as_messages()
 - _No deprecation and no mention in the "What's new" docs._

#1962
Deprecated:
- iris.fileformats.grib.hindcast_workaround
- iris.fileformats.grib.GribWrapper
- iris.fileformats.grib.grib_generator()
 - _Not mentioned in the "What's new" docs_.
Promoted to public API:
- iris.fileformats.grib.GribMessage
- iris.fileformats.grib.Section

**Comment by rhattersley** [comment] 2016-05-10 12:13
> Trying to get my head around what's been going on with the GRIB handling.

Chatting this over with @pelson, he had the (in my opinion) good idea of pulling GRIB support out into a separate package. This lets us decouple its release cycle from the core of Iris. In the short term it helps us get v1.10 out now as a last step before v2.0. In the longer term it fits the strategy of core+extras.

NB. Iris itself would retain the format-picker so as long as you have the new package installed then `iris.load(...)` of a GRIB file would still work - i.e. user code would _not_ need `import new_iris_grib_package` beforehand.

In particular, we propose to roll GRIB support back to v1.9 and deprecate & freeze all of it. In v2.0 all the GRIB support code would be gone and only exist in the new package.

Ping @ajdawson - does this seem like a sane approach?

**Comment by rhattersley** [comment] 2016-05-11 06:27
> we propose to roll GRIB support back to v1.9 and deprecate & freeze all of it

Speaking with @pp-mo yesterday it seems it might be both quicker and kinder to bleeding-edge users to just keep the current modifications[*] instead of rolling back to v1.9. We'd still deprecate everything though, even the new bits that have turned up since v1.9.

[*] We'd still need to re-instate the missing `as_messages()` routine).

@pp-mo - if you can throw up a work-in-progress PR it might possible for others to help, e.g. provide the new FUTURE toggle.

**Comment by ajdawson** [comment] 2016-05-11 09:58
>Ping @ajdawson - does this seem like a sane approach?

I'm not sure it does. I'm not seeing a major benefit of keeping the GRIB code outside of iris, as you will still have problems with what is a major API break and what is not, except you won't be able to control it within iris...

**Comment by rhattersley** [comment] 2016-05-11 10:16
> you will still have problems with what is a major API break and what is not, except you won't be able to control it within iris...

That's a very good point and @pp-mo also raised it yesterday. Further discussion with @pp-mo highlighted that it's a dependency-management issue we already have. For example, two identical installations of Iris but with two different versions of numpy or matplotlib, etc. will give different results. So in general the issue is nothing new and is not specific to Iris - although clearly we would now have _more_ of the issue.

Right now it would give us the freedom to release v1.10 without having to finalise exactly what GRIB support should look like. Instead we could release with `iris.fileformats.grib` deprecated and a pointer to use iris-grib. Once v1.10 is out we could release v2.0 without having to wait for GRIB support to be finalised. Meanwhile, iris-grib could iterate on whatever timescale suits. Similarly, iris-grib could make further major changes without having to wait for a new major Iris release.

**Comment by pp-mo** [comment] 2016-05-11 10:48
> > we propose to roll GRIB support back to v1.9 and deprecate & freeze all of it

> Speaking with @pp-mo yesterday it seems it might be both quicker and kinder to bleeding-edge users to just keep the current modifications instead of rolling back to v1.9....
> @pp-mo - if you can throw up a work-in-progress PR it might possible for others to help, e.g. provide the new FUTURE toggle.

@rhattersley has also suggested a much simpler approach to whole-module deprecation than I had previously achieved...
Method:
 * importing the deprecated module is the only thing that needs to generate a deprecation warning.
 * all other components are imported individually from the (now private) implementation module
 * "__all__" is used to fix the documentation output.
 * plus one tiny complication : documentation of static data items doesn't work ("#: " lines), so those comment lines need to stay in the top-level (now deprecated) module.

This applies beautifully to the iris.fileformats.ff deprecation, so I've now done that as a warmup (see #2010).

I shall next try to apply this to iris.fileformats.grib ...

**Comment by rhattersley** [comment] 2016-05-11 13:01
@ajdawson - I'd rather not press ahead with the iris-grib idea until we can get a consensus. So please do continue to share your thoughts!

Does the idea of moving bits of iris into "satellite" packages concern you in general? Is it the fact that in this case the version of the satellite package directly affects the behaviour of `iris.load(...)`? Or that it's a pile of work with insufficient practical benefit? Or...?

**Comment by ajdawson** [comment] 2016-05-11 14:26
In general having a core of iris with satellite packages sounds like a great idea (this would work particularly well for analysis stuff). However, I'm not sure of the benefits of moving the grib code out of iris. Will it be useful as a standalone project? Is it causing an unnecessary problem to iris that would go away if it is moved outside? I'm struggling to see the motivation here really. To me it sounds like a load of effort, leading to eventual confusion and a maintenance burden, whilst still providing the headaches of API breakage.

I am happy to be convinced otherwise though.

**Comment by rhattersley** [comment] 2016-05-11 14:31
@pelson - can you help shed any light here?

**Comment by pp-mo** [comment] 2016-05-11 16:18
> Will it be useful as a standalone project? 

Really not -- that bothers me, too.
(what it mostly does is translation into Iris cubes.)
From another angle, as iris-grib is totally dependent on iris itself then how is it valuable to separate it ?

**Comment by pelson** [comment] 2016-05-12 09:03
>  However, I'm not sure of the benefits of moving the grib code out of iris. Will it be useful as a standalone project?

No. iris-grib is *completely* dependent upon iris. It is also highly plausible that it is completely dependent upon a specific *version* of iris (or at least a subset of versions).

> leading to eventual confusion and a maintenance burden, whilst still providing the headaches of API breakage

API breakage is very likely. In much the same way that if we update matplotlib without touching iris we run the risk of our plots changing, if we update iris-grib we run the risk of our GRIB file loading changing. Managing that message will be made harder by separating the packages.

So why do it?

Independent release cycles
-------------------------------------

> From another angle, as iris-grib is totally dependent on iris itself then how is it valuable to separate it ?

iris is completely dependent upon numpy, and numpy is completely dependent upon python, yet there is *huge* value from having these as separate packages. By separating the dependant package (iris-grib) we give *it* the freedom to release at its own pace, and *iris* the freedom to release without the burden of iris-grib knowledge.

Choice to the user
------------------------

When we release iris, we are forcing upon the user everything that comes with that version of Iris. If ```iris-grib``` is a separate package, and it expresses its Iris dependency correctly, it will be possible for a user to choose not to upgrade the iris-grib package (in situations where the metadata allows). There is detail here about `iris-grib` being tested against multiple iris versions, and that being expressed correctly in the setup.py, but that is surmountable.

I would probably support a policy of avoiding claiming `iris-grib` compatibility with as-yet unreleased versions of `iris`, and would expect that to be a part of the `iris-grib` packaging metadata that is only updated once a new version of `iris` has been fully unit-tested in its CI.

Smaller iris
---------------

A smaller Iris is a more nimble Iris. Iris will become quicker to test, easier to maintain (at least in the `iris-core` - I accept that there is *more* complexity for the satellite projects), and will enable users to install only the parts which are needed (e.g. many users only use a subset of file types).

-------------

Of course Jupyter are setting a good precedent here - they are rapidly splitting from a monolithic repo into many small packages. Essentially they have taken the approach of starting to benefit from smaller repos and faster release cycles thanks to the improved packaging situation for python.

I suspect we aren't going to come to a conclusion via long messages such as this - I suggest a 30 min Google hangout would be a great way for us to talk the issue through and come to a consensus. What do you think @ajdawson?

**Comment by ajdawson** [comment] 2016-05-12 09:22
Thanks for the detailed point-of-view @pelson. I think your point under "Choice to the user" is extremely compelling actually, and "Smaller iris" is reasonable enough. I don't agree with your assertion under "Independent release cycles", this only makes sense when the package is useful for something else too (like numpy and python).

Back to your "Choice to the user" for a moment. I'd like to have more freedom to modify the GRIB loader and break stuff. Can we manage to separate iris and grib loading in such a way that they are compatible, but different versions of the grib code could produce different results e.g. if I want to rip out the old GRIB1 loading and swap it for a template based loader (and I *do* want to do this!) would that be possible? And second would it be reasonable to say to a user "stick with the old version of the dependency if you want the old behaviour, and upgrade if you want the new" without changing iris version?

**Comment by pelson** [comment] 2016-05-12 09:43
> And second would it be reasonable to say to a user "stick with the old version of the dependency if you want the old behaviour, and upgrade if you want the new" without changing iris version?

I think it would. There is detail here about ensuring that an *old* version of `iris-grib` does support the newer `iris` - there will be situations where that isn't practical and at that point we say "iris-grib needs updating if you want a new iris".

> Can we manage to separate iris and grib loading in such a way that they are compatible, but different versions of the grib code could produce different results

If I'm hearing you correctly, I wouldn't quite go that far - I expect that iris will still need to know about ```iris-grib``` in order to inspect file types and provide a helpful "you need iris-grib to be installed to load GRIB files" when you ```iris.load('fname.grb')```.

There is actually already [machinery](http://scitools.org.uk/iris/docs/v1.9.1/iris/iris/io/format_picker.html#iris.io.format_picker.FormatSpecification) in place to allow you to override the GRIB loader used, but there will always be contention about *which* capability is used if they are both able to load the same files.

All of the above said - separating Iris and iris-grib does mean that we can iterate the latter more quickly if there is more interest there. If we aren't constrained by the major release cycle of Iris, we are able to make major releases of iris-grib as and when is appropriate. IMO getting these major changes into iris-grib may be the best way we reconcile the diverging functionality anyway.

**Comment by ajdawson** [comment] 2016-05-12 09:48
> If we aren't constrained by the major release cycle of Iris, we are able to make major releases of iris-grib as and when is appropriate.

This is true, but will we be able to use a new major release of iris-grib within iris without making a new major version of iris? I don't know if we can easily answer that question.

**Comment by pelson** [comment] 2016-05-12 09:57
> This is true, but will we be able to use a new major release of iris-grib within iris without making a new major version of iris? I don't know if we can easily answer that question.

In what sense? Technically I think it is perfectly possible, so it comes down to an appetite thing. We don't demand a new Python release when we release Iris, so why should `iris-grib` demand a new `iris` (I am, of course, taking the argument to the extreme).

**Comment by ajdawson** [comment] 2016-05-12 10:29
I meant the other way around. If we change iris-grib to a new major version, will Iris realistically be able to take advantage without needing a major version change of its own?

**Comment by rhattersley** [comment] 2016-05-12 10:49
> If we change iris-grib to a new major version, will Iris realistically be able to take advantage without needing a major version change of its own?

Yes, I think so. For me that was actually one of the main drivers. Iris will only depend on a small part of the iris-grib API (e.g. what is currently `iris.fileformats.grib.save_grib2()` and `iris.fileformats.grib.load_cubes()`). All the other stuff about GribMessages, message generators, etc., etc. can undergo backwards incompatible changes without needing iris to change.

**Comment by pp-mo** [comment] 2016-05-12 11:57
> > If we change iris-grib to a new major version, will Iris realistically be able to take advantage without needing a major version change of its own?

> @rhattersley Yes, I think so.

.

> @ajdawson I don't agree with your assertion under "Independent release cycles",

> > @pelson By separating the dependant package (iris-grib) we give it the freedom to release at its own pace

> this only makes sense when the package is useful for something else too (like numpy and python).

I think I can illuminate this with a real practical example:

At present, we have users who need to load "mixed" Grib files, containing both edition-1 and edition-2 messages.  The only way to do this at present is to use the "old" loader mechanism.
The old mechanism is deprecated, and we want to retire it, but we can't do that until we have a replacement solution for this functionality, which we still aren't quite ready to do.
In addition, the old loader presents a different message object to load callbacks, which can make rewriting existing code somewhat non-trivial.

We would really like to remove the "old" loader at iris 2.0.
According to our current "release rules", that means we must **first** release an alternative solution for Grib1 support via the new loader, so that these users can stop using the old one.
**So that is currently a blocker on 1.10.**

If instead we deprecate the whole of iris.fileformats.grib in favour of "iris-grib", then everyone can easily make that migration quite soon.
We can then remove iris.fileformats.grib from iris 2.0 without further complication.
When ready, we can release "newstyle grib1 support", and then remove the old loader at iris-grib v2.0.
None of this necessarily affects the *general* compatibility of Iris with iris-grib, so it doesn't provoke further iris revisions (though it can affect how, or if, certain files load).
It also makes it possible to upgrade to iris 2.0 without further changes to existing code, while still using iris-grib 1.0 for the old loader if you really want it.

**Comment by ajdawson** [comment] 2016-05-12 11:59
OK, I'm in. I want more gribby goodness and this seems like a good way for me to get it!

**Comment by rhattersley** [comment] 2016-08-03 08:08
The runtime deprecation warning for `iris.FUTURE.strict_iris_grib` can be misleading:
* `IrisDeprecation: the 'Future' object property 'strict_grib_load' is now deprecated. Please remove code which uses this.`

It was only when I happened across the help text for the `iris.Future` class (as research prior to raising a GitHub issue) that I spotted the much more useful advice relating to the `iris_grib` package.

Please could you consider adding the more verbose description to the runtime warning? (Given the significance of the iris_grib change, I would suggest that easing that transition should be a 1.10 release blocker.)

**Comment by pp-mo** [comment] 2016-08-11 10:04
See #2112
Addresses the issue, but is it too much fuss ?

**Comment by marqh** [comment] 2016-08-31 14:21
this is now complete, as far as i can see

**Closed by marqh** 2016-08-31 14:21 UTC
Labels: ready
