### ISSUE TITLE
Proj4 v6.x causing issues with conda install

### ISSUE THREAD

**Issue by kaedonkers** [SciTools/iris#3646] opened 2020-01-24 10:27 UTC
Hello,

With a recent conda install of Iris, plotting data gets messed-up projections:
`conda install -c conda-forge iris`
![image](https://user-images.githubusercontent.com/32906197/73061710-b8839580-3e92-11ea-9ab5-9c4e553c22c7.png)

I managed to solve this by installing Iris with Proj4 pinned to v5 (which also downgraded pyproj to v1.9.x):
`conda install -c conda-forge iris proj4=5`
![image](https://user-images.githubusercontent.com/32906197/73061755-cafdcf00-3e92-11ea-9eb0-a4c317588d79.png)

The latest Iris docs states that it [does not support Proj4 above v5](https://scitools.org.uk/iris/docs/latest/whatsnew/2.3.html#iris-2-3-0-dependency-updates), pointing to this [Cartopy issue](https://github.com/SciTools/cartopy/pull/1289#pullrequestreview-272774087).

I checked the conda-forge feedstock for Iris and it does not pin Proj4:
https://github.com/conda-forge/iris-feedstock/blob/master/recipe/meta.yaml

Pending the fix to Cartopy, could you perhaps pin Proj4 to v5.x in the meantime?

Thanks 😄

**Comment by pp-mo** [comment] 2020-01-24 11:32
Hi @kaedonkers !
Pinning in the iris repo (i.e. the requirements files) can only affect pip installation, *is that what you needed to fix ?*  Because otherwise, to pin *conda* installs, we need to fix it in the conda-forge repo.

I guess that statement in the docs is just a pragmatic warning.  It only applies to 2.3.0, so conceivably this might not even be true still, but from your experience I guess it is.

I think we didn't like to actually pin this in the iris recipe as it's really a Cartopy issue !  IIRC there is no direct proj4 usage or dependency in Iris, it's only via Cartopy.
Which is awkward, because the above Cartopy issue is now closed, and Cartopy is happily testing and building against proj4 v6, yet the problems apparently remain ...

Regardless of Iris dependencies and problems,  it does seem to me that this is an outstanding issue with Cartopy itself, and needs to be back-converted to a cartopy-only problem + dealt with there.

You don't give enough info above to determine the actual projection being used -- ***can you get this down to a simply reproducible case, even if still coded using Iris ?***

**Comment by kaedonkers** [comment] 2020-01-24 11:49
Hi @pp-mo!

1. Yes, it should really be a [`conda-forge/iris-feedstock`](https://github.com/conda-forge/iris-feedstock) Issue but I thought it'd get more attention here 😋 

2. This problem was reproducible installing older versions of Iris, hence my conclusion that it's a Proj4 pinning issue.

3. Yep, I guess it really is a Cartopy issue. However I don't currently have time to recreate it in Cartopy. Would raising an issue with the [`conda-forge/cartopy-feedstock`](https://github.com/conda-forge/cartopy-feedstock) be the best next move?

**Comment by pp-mo** [comment] 2020-01-24 12:06
> Would raising an issue with the conda-forge/cartopy-feedstock be the best next move?

It's quickest I think.  It should be a really small fix, and if you increment build number then I guess it will override the existing with 2.3.0 builds which are having this problem.

>  I don't currently have time to recreate it in Cartopy

If you can just post the necessary to reproduce the above example, I'd be happy could chase it down to the Cartopy level and (re-)raise it there.

**Comment by trexfeathers** [comment] 2021-01-15 09:25
Closed by #3762

**Closed by trexfeathers** 2021-01-15 09:25 UTC
