### ISSUE TITLE
Multiplication issue related to change in Iris 1.13

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2698] opened 2017-07-28 14:43 UTC
I have noticed a change of behaviour between Iris 1.12 and Iris 1.13 related to multiplying cubes, where one cube is from an ancillary file.

For Iris 1.12:

```
% module load scitools/default-previous
% ipython
Python 2.7.12 | Met Office - SciTools | (default, Sep 22 2016, 17:01:57) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import iris

In [2]: print iris.__version__
1.12.0

In [3]: cube = iris.load_cube('ajnjga.pmm1jan.pp', iris.AttributeConstraint(STASH='m01s19i013') & iris.Constraint(pseudo_level=4))

In [4]: ancil = iris.load_cube('mask_frac_l32161_n96_ref_orig.pp')

In [5]: print cube
m01s19i013                          (latitude: 145; longitude: 192)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
     Scalar coordinates:
          forecast_period: 1400040.0 hours, bound=(1399680.0, 1400400.0) hours
          forecast_reference_time: 1859-01-01 00:00:00
          pseudo_level: 4
          time: 2021-01-16 00:00:00, bound=(2021-01-01 00:00:00, 2021-02-01 00:00:00)
     Attributes:
          STASH: m01s19i013
          source: Data from Met Office Unified Model
          um_version: 6.6
     Cell methods:
          mean: time (240 hour)

In [6]: print ancil
land_area_fraction / (1)            (latitude: 145; longitude: 192)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
     Scalar coordinates:
          height: 0.0 m
          time:    1-01-01 00:00:00
     Attributes:
          STASH: m01s00i505
          source: Data from Met Office Unified Model

In [7]: new_cube = cube * ancil

In [8]: print new_cube 
unknown / (unknown)                 (latitude: 145; longitude: 192)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
     Scalar coordinates:
          forecast_period: 1400040.0 hours, bound=(1399680.0, 1400400.0) hours
          forecast_reference_time: 1859-01-01 00:00:00
          pseudo_level: 4
          time: 2021-01-16 00:00:00, bound=(2021-01-01 00:00:00, 2021-02-01 00:00:00)
```

Iris 1.13:

```
% module load scitools/default-current
% ipython
Python 2.7.12 | Met Office - SciTools | (default, Sep 22 2016, 17:01:57) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import iris

In [2]: print iris.__version__
1.13.0

In [3]: cube = iris.load_cube('ajnjga.pmm1jan.pp', iris.AttributeConstraint(STASH='m01s19i013') & iris.Constraint(pseudo_level=4))

In [4]: ancil = iris.load_cube('mask_frac_l32161_n96_ref_orig.pp')

In [5]: print cube
m01s19i013                          (latitude: 145; longitude: 192)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
     Scalar coordinates:
          forecast_period: 1400040.0 hours, bound=(1399680.0, 1400400.0) hours
          forecast_reference_time: 1859-01-01 00:00:00
          pseudo_level: 4
          time: 2021-01-16 00:00:00, bound=(2021-01-01 00:00:00, 2021-02-01 00:00:00)
     Attributes:
          STASH: m01s19i013
          source: Data from Met Office Unified Model
          um_version: 6.6
     Cell methods:
          mean: time (240 hour)

In [6]: print ancil
land_area_fraction / (1)            (latitude: 145; longitude: 192)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
     Scalar coordinates:
          height: 0.0 m
          time:    1-01-01 00:00:00
     Attributes:
          STASH: m01s00i505
          source: Data from Met Office Unified Model

In [7]: new_cube = cube * ancil

In [8]: print new_cube
unknown / (unknown)                 (latitude: 145; longitude: 192)
     Dimension coordinates:
          latitude                           x               -
          longitude                          -               x
```

Where did all the scalar coordinates go?! :stuck_out_tongue_winking_eye:

This might be related to the following bug fix (as detailed on http://scitools.org.uk/iris/docs/v1.13.0/whatsnew/1.13.html):

An error is now correctly raised if a user tries to perform an arithmetic operation on two cubes with mismatching coordinates. Previously these cases were caught by the add and subtract operators, and now it is also caught by the multiply and divide operators.

However, no exception is raised in this case. Is this expected? Would it be possible for Iris 1.13 to retain the scalar coordinates?

**Comment by rcomer** [comment] 2017-07-30 14:55
Hi @ehogan, this part of Iris is being actively looked at in #2599.  I don't think anyone has yet given an opinion there on what happens to the scalar coords though.  There was some discussion at #1911, where you will see I am all for keeping them 🙂.

**Comment by ehogan** [comment] 2017-07-31 09:31
That's useful; thanks @rcomer! :)

**Comment by pelson** [comment] 2018-01-03 20:40
Closing as a duplicate of #2599 (I appreciate that it isn't *exactly* a duplicate, but solving that will solve this). Thanks for raising.

**Closed by pelson** 2018-01-03 20:40 UTC
