### ISSUE TITLE
merge to accept variable_name clashes

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#512] opened 2013-05-20 14:54 UTC
[This discussion](https://groups.google.com/forum/#!topic/scitools-iris/1hKRB7Q0TZo) highlighted that variable names loaded from NetCDF files are used in the comparison of candidate cubes during merge.

Variable names are not semantic containers, they are just labels, and should not be treated in this way.  This needs to be implemented for cubes and coordinates, both exhibit the behaviour.

Update merge such that it:
- preserves 1 variable name if it is consistent across all candidate cubes/coordinates
- removes variable names from candidate cubes/coordinates if they differ, enabling merging to occur

Test suggestion: slice a cube into a cubelist and save the cubelist as a NetCDF file.  Load the NetCDF file and assert that the merge result in 1 cube, ignoring the differing variable names.

**Comment by trexfeathers** [comment] 2022-06-29 09:37
Duplicate of #4446

**Closed by trexfeathers** 2022-06-29 09:37 UTC
Labels: Feature: merge/concatenate, Peloton 🚴‍♂️
