### ISSUE TITLE
iris.util.unify_time_units changes time points dtype

### ISSUE THREAD

**Issue by PAGWatson** [SciTools/iris#3213] opened 2018-11-05 18:47 UTC
Hello, I just spent quite a long time figuring out why two cubes would not concatenate. It turned out to be because I had used iris.util.unify_time_units on them, and this had turned the time coordinate points dtype for one cube from int64 to float64. This was very hard to track down because the dtype is not displayed when the coordinate is printed. I suggest that iris.util.unify_time_units also makes sure the coordinate dtypes are compatible.

**Comment by rcomer** [comment] 2020-09-25 15:54
Hi @PAGWatson, do you know if this still happens for your use-case?  A similar problem reported at #1036 seems to have been fixed some time before Iris 2.4 was released.

**Comment by PAGWatson** [comment] 2020-09-25 16:06
Thanks for following up. I'm afraid I can't remember what action gave me this error before, so I can't try to reproduce it right now.

**Comment by rcomer** [comment] 2021-05-01 21:09
I’m going to close this one, since there is reason to believe it is fixed and we don’t currently have a way to reproduce the problem.  Obviously if anyone stumbles on the problem again, they can open a new issue, or we can re-open this one.

**Closed by rcomer** 2021-05-01 21:09 UTC
