### ISSUE TITLE
minimal/lazy iris imports

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#1994] opened 2016-04-29 11:39 UTC
Remove unnecessary imports which occur as a consequence of

```
import iris
```

**Comment by rhattersley** [comment] 2016-05-04 15:17
e.g. Is it _really_ necessary to import scipy?

**Comment by davidnmurray** [comment] 2016-05-25 16:23
I've been doing some investigation into this issue (see ticket 1214 in JIRA). Running pylint to look for unused imports, I found a large number of 'import six' and 'from six.moves...' statements that didn't appear to be used for anything. So I made a local branch of my iris to experiment on, and took all of these statements out. The modified iris still works correctly - it can reproduce everything in the user guide - but several of the tests fail. (These are test_cdm.py, test_coding_standards.py,  and test_check_contributions.)

So given that, it looks like these statements are still needed. 

Pylint did flag up a few other items, but the number was quite small, so I suppose there is a question whether it's useful to make a pull request here?

**Comment by ajdawson** [comment] 2016-05-25 16:44
Most of the six imports are there by design, even if they aren't used, particularly `six.moves`. These are there to help ensure we write code that works the same on Python 2 and 3 (e.g. `six.moves.range` is always a generator, equivalent to `xrange` on Python 2 and built-in `range` on Python 3, so when someone writes new code using `range` in a module importing `six.moves.range` it behaves the same on PYthon 2 and 3).

**Comment by QuLogic** [comment] 2016-05-25 18:13
Does pylint not respect the `# noqa` on the `six.moves` imports?

**Comment by ajdawson** [comment] 2016-05-25 18:25
I guess not, seems to work for flake8 and pep8.

**Comment by lbdreyer** [comment] 2016-05-26 12:11
> Pylint did flag up a few other items, but the number was quite small, so I suppose there is a question whether it's useful to make a pull request here?

@davidnmurray It is still worthwhile to create a PR that removes the unused imports even if there's only a few. 

Remember small PRs are a good thing! They are quick and easy to merge in.

**Comment by rcomer** [comment] 2021-09-24 17:29
Was this resolved by #4174, or is there more to do here?

**Comment by pp-mo** [comment] 2021-09-27 11:27
>  resolved by #4174 ?

Yes, I think we're done.

**Closed by pp-mo** 2021-09-27 11:27 UTC
Labels: Type: Performance, Experience: Low, Good First Issue
