### ISSUE TITLE
Concatenate not equivalent to merge.

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#1527] opened 2015-01-12 14:29 UTC
Stumbled over a case with files containing data at different timepoints.  Each file gives a *1 time dimension (owing to netcdf representation) : Making the time coordinates *scalar* allows these all to merge correctly.  However, the *original* data will not concatenate (which ought to be an equivalent operation).
Not yet found what may be causing this.

N.B. example data, but unfortunately large, attached to internal issue : EPM-691
TODO: chase this up + produce testcase with small data.

**Comment by ajdawson** [comment] 2015-06-19 09:40
Just had an issue on Google Groups that exhibited this symptom (https://groups.google.com/forum/?fromgroups#!topic/scitools-iris/LWXXvObs-mw). Looks like it was fixed in v1.7.3 though. Are you able to check if this is still an issue on v1.7.4 or v1.8.1 @pp-mo?

**Comment by pelson** [comment] 2015-06-22 15:50
I'll close this as it wasn't really reproducible. I've taken a look at @pp-mo's referenced (internal) ticket, and even there, the data moved mid investigation (hence the problem with isolation I believe).

Thanks @ajdawson!

**Closed by pelson** 2015-06-22 15:50 UTC
